import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Next Daisy Template",
  description: "Generated by create next app, with daisyUI and Tailwind CSS.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh" suppressHydrationWarning>
      <body className="h-full min-h-screen">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
